server:
  tomcat:
    threads:
      max: 1000
      min-spare: 500
    accept-count: 1000
    max-connections: 10000

spring:
  config:
    activate:
      on-profile: docker

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: 10000ms
      lettuce:
        pool:
          max-active: 200
          max-idle: 50
          min-idle: 20
          max-wait: 3000ms

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?currentSchema=${DB_SCHEMA:queue_service}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA:queue_service}
        hbm2ddl:
          create_schemas: true

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://eureka-server:10001/eureka/}

management:
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  tracing:
    sampling:
      probability: 0.1
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411/api/v2/spans}

feign:
  circuitbreaker:
    enabled: true
resilience4j:
  circuitbreaker:
    instances:
      default:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        record-exceptions:
          - feign.RetryableException
          - java.io.IOException
          - java.util.concurrent.TimeoutException

  retry:
    instances:
      default:
        max-attempts: 3
        wait-duration: 500ms
        retry-exceptions:
          - java.lang.Exception

queue:
  token:
    secret: ${QUEUE_TOKEN_SECRET}
